"""Docker Compose platform adapter — renders per-service environment variable maps."""

from dsql_config.adapters.ecs import _DSQL_ENV_MAP
from dsql_config.models import ConfigProfile, RenderedSnippet


class ComposeAdapter:
    platform: str = "compose"
    name: str = "Docker Compose"

    def render(self, profile: ConfigProfile) -> list[RenderedSnippet]:
        snippets: list[RenderedSnippet] = []

        # Shared .env file for DSQL settings
        shared_lines = self._render_shared_env(profile)
        snippets.append(
            RenderedSnippet(
                language="dotenv",
                filename="dsql.env",
                content=shared_lines,
            )
        )

        # Per-service replica counts
        for service in ("history", "matching", "frontend", "worker"):
            p = profile.get_param(f"{service}.replicas")
            if p:
                snippets.append(
                    RenderedSnippet(
                        language="dotenv",
                        filename=f"{service}.env",
                        content=f"TEMPORAL_{service.upper()}_REPLICAS={p.value}\n",
                    )
                )

        return snippets

    @staticmethod
    def _render_shared_env(profile: ConfigProfile) -> str:
        lines: list[str] = [
            "# Generated by temporal-dsql-config",
            f"# Preset: {profile.preset_name}",
            "",
        ]
        for key, env_name in _DSQL_ENV_MAP.items():
            p = profile.get_param(key)
            if p:
                value = str(p.value).lower() if isinstance(p.value, bool) else str(p.value)
                lines.append(f"{env_name}={value}")

        return "\n".join(lines) + "\n"
