"""Go SDK adapter — renders Go worker option configuration from a ConfigProfile."""

from dsql_config.models import ConfigProfile, RenderedSnippet


class GoSDKAdapter:
    language: str = "go"
    name: str = "Go SDK"

    def render(self, profile: ConfigProfile) -> RenderedSnippet:
        lines: list[str] = [
            "// Generated by temporal-dsql-config",
            f"// Preset: {profile.preset_name}"
            + (f" + {profile.modifier}" if profile.modifier else ""),
            "",
            "workerOptions := worker.Options{",
        ]

        param_map = {
            "sdk.max_concurrent_activities": "MaxConcurrentActivityExecutionSize",
            "sdk.max_concurrent_workflow_tasks": "MaxConcurrentWorkflowTaskExecutionSize",
            "sdk.max_concurrent_local_activities": "MaxConcurrentLocalActivityExecutionSize",
            "sdk.workflow_task_pollers": "MaxConcurrentWorkflowTaskPollers",
            "sdk.activity_task_pollers": "MaxConcurrentActivityTaskPollers",
            "sdk.disable_eager_activities": "DisableEagerActivities",
        }

        for key, go_field in param_map.items():
            p = profile.get_param(key)
            if p:
                value = str(p.value).lower() if isinstance(p.value, bool) else str(p.value)
                lines.append(f"    {go_field}: {value},")

        # Sticky timeout needs special formatting
        sticky = profile.get_param("sdk.sticky_schedule_to_start_timeout")
        if sticky:
            val = str(sticky.value)
            if val.endswith("s"):
                lines.append(f"    StickyScheduleToStartTimeout: {val[:-1]} * time.Second,")
            elif val.endswith("m"):
                lines.append(f"    StickyScheduleToStartTimeout: {val[:-1]} * time.Minute,")

        lines.append("}")
        return RenderedSnippet(
            language="go", filename="worker_options.go", content="\n".join(lines)
        )
