"""Python SDK adapter — renders Python worker configuration from a ConfigProfile."""

from dsql_config.models import ConfigProfile, RenderedSnippet


class PythonSDKAdapter:
    language: str = "python"
    name: str = "Python SDK"

    def render(self, profile: ConfigProfile) -> RenderedSnippet:
        lines: list[str] = [
            "# Generated by temporal-dsql-config",
            f"# Preset: {profile.preset_name}"
            + (f" + {profile.modifier}" if profile.modifier else ""),
            "",
            "from temporalio.worker import Worker",
            "",
            "worker = Worker(",
            "    client=client,",
            '    task_queue="your-task-queue",',
            "    workflows=[...],",
            "    activities=[...],",
        ]

        param_map = {
            "sdk.max_concurrent_activities": "max_concurrent_activities",
            "sdk.max_concurrent_workflow_tasks": "max_concurrent_workflow_tasks",
            "sdk.max_concurrent_local_activities": "max_concurrent_local_activities",
        }

        for key, py_field in param_map.items():
            p = profile.get_param(key)
            if p:
                lines.append(f"    {py_field}={p.value},")

        lines.append(")")
        return RenderedSnippet(
            language="python", filename="worker_config.py", content="\n".join(lines)
        )
